### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by adinarayanaraghu** [smarty24/smartyano.bplaced.net-jobboard#1]
Hello there. 
Didn't know where else to contact you, 

Is there a way you could integrate this project for one of the open source educational platform for the benefit of student community? 

If yes, please send me a mail at adinarayanaraghu95@gmail.com

**Comment by kelechi-onyia** [comment]
Hi there,
Thank you for taking interest in my project. I am not sure if I understand what you want me to do. I am happy to help in anyway I can.
